(() => {
 'use strict';
 const E=EnigmaCore, A=E.ABC, $=id=>document.getElementById(id), rows=['QWERTZUIO','ASDFGHJK','PYXCVBNML'];
 const MAX=10000, STORAGE='enigma-lab-v1';
 let config=E.defaultConfig(), machine=new E.Machine(config), source='', normalized='', traces=[], running=false,timer=0,activeTab='machine',inspect=-1;
 let sound=false,audioContext=null,lampTimer=0,toastTimer=0,saveTimer=0,editConfig=null,pendingPlug=null,storageEnabled=false;
 const letters=p=>p.map(n=>A[n]).join(''), grouped=s=>$('groupOutput').checked?(s.match(/.{1,5}/g)||[]).join(' '):s;
 const output=()=>traces.map(t=>t.output).join('');
 function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3400);}
 function announce(text){$('liveStatus').textContent=text;}
 function setTab(name){const changed=activeTab!==name;activeTab=name;document.querySelectorAll('[data-tab]').forEach(b=>{const on=b.dataset.tab===name;b.setAttribute('aria-selected',on);b.tabIndex=on?0:-1;});for(const n of ['machine','signal','codebook','guide'])$('pane-'+n).hidden=n!==name;if(name==='signal')renderTrace();if(changed&&matchMedia('(max-width:1023px)').matches)$('pane-'+name).scrollIntoView({block:'start',behavior:'auto'});}
 function tickSound(){if(!sound)return;try{if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume().catch(()=>{});const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='triangle';o.frequency.setValueAtTime(260,audioContext.currentTime);o.frequency.exponentialRampToValueAtTime(70,audioContext.currentTime+.04);g.gain.setValueAtTime(.045,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.055);o.connect(g);g.connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+.06);}catch(e){sound=false;$('soundBtn').textContent='Âm thanh: Tắt';$('soundBtn').setAttribute('aria-pressed','false');}}
 function flash(trace){clearTimeout(lampTimer);document.querySelectorAll('.lamp.on,.keycap.pressed').forEach(el=>el.classList.remove('on','pressed'));if(!trace)return;$('lamp-'+trace.output).classList.add('on');$('key-'+trace.input).classList.add('pressed');$('lampStatus').textContent='ĐÈN '+trace.output+' · '+trace.input+' → '+trace.output;lampTimer=setTimeout(()=>{document.querySelectorAll('.lamp.on,.keycap.pressed').forEach(el=>el.classList.remove('on','pressed'));$('lampStatus').textContent='MẠCH ĐIỆN SẴN SÀNG';},Math.min(750,running?1000/Number($('speed').value)*.8:750));}
 function initKeys(){rows.forEach(row=>{const lamps=document.createElement('div'),keys=document.createElement('div');lamps.className=keys.className='key-row';[...row].forEach(c=>{const l=document.createElement('div');l.className='lamp';l.id='lamp-'+c;l.textContent=c;l.setAttribute('aria-label','Đèn '+c);lamps.append(l);const k=document.createElement('button');k.type='button';k.className='keycap';k.id='key-'+c;k.textContent=c;k.setAttribute('aria-label','Nhấn phím '+c);k.addEventListener('click',()=>manualPress(c));keys.append(k);});$('lampboard').append(lamps);$('keyboard').append(keys);});}
 function buildRotors(){const n=config.rotors.length;$('rotorBank').closest('.machine').classList.toggle('m4',n===4);$('rotorBank').innerHTML='';config.rotors.forEach((name,i)=>{const unit=document.createElement('div');unit.className='rotor-unit';unit.innerHTML=`<div class="rotor-name">${name==='Beta'?'β BETA':name==='Gamma'?'γ GAMMA':name}</div><button class="rotor-adjust" data-rotor="${i}" data-delta="-1" aria-label="Lùi rotor ${name}">▴</button><div class="rotor-slot" id="rotor-slot-${i}"><span class="rotor-letter" id="rotor-letter-${i}">A</span><span class="rotor-teeth"></span></div><button class="rotor-adjust" data-rotor="${i}" data-delta="1" aria-label="Tăng rotor ${name}">▾</button><div class="rotor-ring" id="rotor-info-${i}"></div>`;$('rotorBank').append(unit);});$('rotorBank').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{if(traces.length||running)return;const i=Number(b.dataset.rotor);config.positions[i]=E.mod(config.positions[i]+Number(b.dataset.delta));machine=new E.Machine(config);update();saveSoon();}));$('modelTitle').textContent=config.model==='I'?'Enigma I':'Enigma '+config.model;$('machinePlate').textContent=n+' ROTOREN · UKW '+config.reflector;$('reflectorBadge').textContent=config.reflector.replace('-thin','′');}
 function drawRotors(trace){config.rotors.forEach((name,i)=>{const p=machine.positions[i],letter=$('rotor-letter-'+i);letter.textContent=A[p];letter.classList.remove('stepped');if(trace&&trace.stepped[i]){void letter.offsetWidth;letter.classList.add('stepped');}const atNotch=E.RAW[name][1].includes(A[p]);$('rotor-slot-'+i).classList.toggle('at-notch',atNotch);$('rotor-slot-'+i).title=atNotch?'Đang ở rãnh kéo: '+A[p]:'Cửa sổ '+A[p]+' / '+String(p+1).padStart(2,'0');$('rotor-info-'+i).textContent=(config.model==='I'?String(p+1).padStart(2,'0')+' · ':'')+'R '+A[config.rings[i]]+(config.model==='M4'&&i===0?' · TĨNH':'');});document.querySelectorAll('.rotor-adjust').forEach(b=>{b.disabled=traces.length>0||running;b.title=traces.length?'Về đầu để chỉnh vị trí khởi đầu':'Xoay cửa sổ khởi đầu';});}
 function update(trace){drawRotors(trace);$('messageInput').value=source;$('messageInput').disabled=running;$('sampleSelect').disabled=running;const n=traces.length,total=normalized.length,done=total>0&&n===total;
  $('inputCount').textContent=total.toLocaleString('vi-VN')+' KÝ TỰ A–Z';$('outputText').textContent=grouped(output());$('outputCount').textContent=n+' / '+total;$('countDisplay').textContent=String(n).padStart(4,'0');$('startDisplay').textContent=letters(config.positions);$('positionDisplay').textContent=letters(machine.positions);$('currentWindow').textContent='CỬA SỔ · '+[...letters(machine.positions)].join(' ');$('lastPair').textContent=n?traces[n-1].input+' → '+traces[n-1].output:'— → —';
  $('progressFill').style.width=(total?n/total*100:0)+'%';$('progress').setAttribute('aria-valuenow',total?Math.round(n/total*100):0);
  $('playBtn').textContent=running?'Ⅱ Tạm dừng':done?'↺ Chạy lại':'▶ Chạy bản tin';$('playBtn').disabled=!total;$('dockPlay').disabled=!total;$('dockPlay').textContent=running?'Ⅱ Dừng':done?'↺ Chạy lại':'▶ Chạy';$('stepBtn').disabled=running||n>=total;$('fastBtn').disabled=running||n>=total;$('undoBtn').disabled=!n||running;$('rewindBtn').disabled=!n&&!running;$('decryptBtn').disabled=!n||running;$('copyBtn').disabled=!n;$('exportText').disabled=!n;
  $('keyboardHint').textContent=running?'Đang tự chạy bản tin…':n<total?'Bấm Chạy bản tin hoặc Từng phím để xử lý nội dung đã nhập.':'Bấm phím tròn hoặc nhấp vào bàn phím rồi gõ A–Z.';
  document.querySelectorAll('.keycap').forEach(k=>k.disabled=running||n<total||total>=MAX);
  $('sessionStatus').textContent=running?'Đang chạy; mỗi phím sẽ quay rotor trước.':done?'Hoàn tất. Có thể giải mã kết quả bằng cùng khóa.':n?'Tạm dừng tại bước '+n+'.':total?'Nội dung đã sẵn sàng. Bấm Chạy bản tin.':'Sẵn sàng nhận bản tin.';
  $('settingsSummary').textContent='KHÓA: '+config.rotors.join(' · ')+' / RING '+letters(config.rings)+' / UKW '+config.reflector+' / '+config.plugs.length+' cặp dây. Cửa sổ được đặt trước phím đầu tiên.';
  $('plugSummary').innerHTML=config.plugs.length?config.plugs.map(p=>`<span class="pair-chip">${p[0]} ↔ ${p[1]}</span>`).join(''):'<span class="muted" style="font-size:11px">Chưa nối dây · Các chữ đi thẳng qua plugboard.</span>';
  if(activeTab==='signal')renderTrace();
 }
 function clearRun(){pause(false);machine=new E.Machine(config);traces=[];inspect=-1;flash(null);$('lampStatus').textContent='MẠCH ĐIỆN SẴN SÀNG';}
 function reset(keepText=true){clearRun();if(!keepText){source='';normalized='';$('presetNotice').hidden=true;}$('inputError').hidden=true;update();saveSoon();}
 function useConfig(c,text='',notice=''){config=E.validate(c);clearRun();source=text;normalized=E.normalize(source);buildRotors();$('presetNotice').hidden=!notice;$('presetNotice').textContent=notice;$('inputError').hidden=true;update();saveSoon();}
 function pressNext(render=true){if(traces.length>=normalized.length)return false;const t=machine.press(normalized[traces.length]);traces.push(t);inspect=-1;if(render){tickSound();flash(t);update(t);}return true;}
 function pause(render=true){clearTimeout(timer);running=false;if(render){update();saveSoon();}}
 function schedule(){if(!running)return;if(!pressNext()){pause();announce('Hoàn tất bản tin '+traces.length+' ký tự.');return;}saveSoon();timer=setTimeout(schedule,1000/Number($('speed').value));}
 function play(){if(running){pause();return;}if(!normalized)return;if(traces.length===normalized.length)clearRun();running=true;update();schedule();}
 function next(){pause(false);if(pressNext())saveSoon();else toast('Nhập nội dung hoặc nạp ví dụ trước.');}
 function fast(){pause(false);while(pressNext(false)){}const t=traces.at(-1);flash(t);update(t);saveSoon();announce('Hoàn tất '+traces.length+' ký tự.');}
 function undo(){pause(false);if(!traces.length)return;const t=traces.pop();machine.positions=[...t.before];inspect=-1;flash(traces.at(-1));update();saveSoon();}
 function manualPress(c){if(running)return;if(traces.length<normalized.length){toast('Hãy chạy hết nội dung đang chờ trước khi gõ trực tiếp.');return;}if(normalized.length>=MAX){toast('Đã đạt giới hạn 10.000 chữ cho một phiên.');return;}source+=c;normalized+=c;pressNext();saveSoon();}
 function preset(name){let c=E.defaultConfig(),text='',notice='';if(name==='hello'){text='HELLO WORLD';notice='Ví dụ chuẩn: HELLOWORLD → ILBDAAMTAZ. Bấm Chạy bản tin để quan sát.';}else if(name==='double'){c.positions=[0,3,20];text='AAA';notice='Bấm Từng phím 3 lần: ADU → ADV → AEW → BFX. Rotor giữa quay ở cả bước 2 và 3.';}else if(name==='naval'){c=E.defaultConfig('M4');c.rotors=['Beta','II','IV','VI'];c.rings=[0,1,4,11];c.positions=[12,0,0,0];c.plugs=E.parsePlugs('AV BS CG DL FU HZ IN KM OW RX');text='DIES IST EIN TEST';notice='Ví dụ học tập M4. Quan sát rotor Beta ở M đứng yên trong cả bản tin.';}else if(name==='vector'){c.rotors=['II','IV','V'];c.rings=[1,20,11];c.positions=[1,11,0];c.plugs=E.parsePlugs('AV BS CG DL FU HZ IN KM OW RX');text='THEXRUSSIANSXAREXCOMINGX';notice='Vector Py-Enigma: kết quả phải là NIBLFMYMLLUFWCASCSSNVHAZ.';}else return;useConfig(c,text,notice);$('sampleSelect').value='';setTab('machine');}
 function selectTrace(i){inspect=Math.max(0,Math.min(traces.length-1,i));renderTrace();}
 function renderTrace(){const total=traces.length,index=inspect<0?total-1:inspect,t=traces[index],p=t?t.after:machine.positions;
  $('tracePair').textContent=t?t.input+' → '+t.output:'— → —';$('tracePrev').disabled=!t||index<=0;$('traceNext').disabled=!t||index>=total-1;$('signalStep').disabled=running||total>=normalized.length;$('signalPlay').disabled=!normalized;$('signalPlay').textContent=running?'Ⅱ Dừng':'▶ Chạy';
  // Display a bounded list for large messages; the whole history remains in the export.
  let options=total?'<option value="-1">Mới nhất · bước '+total+'</option>':'<option value="-1">Chưa có dữ liệu</option>';
  const lo=Math.max(0,total-250);if(inspect>=0&&inspect<lo)options+=`<option value="${inspect}">Bước ${inspect+1} · ${t.input} → ${t.output}</option>`;
  for(let i=lo;i<total;i++)options+=`<option value="${i}">Bước ${i+1} · ${traces[i].input} → ${traces[i].output}</option>`;
  $('traceSelect').innerHTML=options;$('traceSelect').value=String(inspect);
  let explain='Chưa có phím bấm. Sơ đồ đang hiển thị dây nối tại cấu hình hiện tại.';
  if(t){const turned=t.stepped.map((v,i)=>v?config.rotors[i]:null).filter(Boolean).join(', ');explain='Bước '+(index+1)+': '+letters(t.before)+' → '+letters(t.after)+'. Rotor quay: '+turned+'. ';if(t.middleNotch)explain+='Rotor giữa đang ở rãnh trước phím bấm, nên rotor trái và giữa cùng quay. '+(index>0&&traces[index-1].stepped[config.rotors.length-2]?'Đây là bước thứ hai liên tiếp của rotor giữa (double-stepping).':'');else if(t.rightNotch)explain+='Rotor phải đang ở rãnh trước phím bấm, kéo rotor giữa quay theo.';else explain+='Chỉ rotor phải quay một nấc.';}
  $('stepExplain').textContent=explain;$('signalStages').innerHTML=t?t.stages.map(s=>`<div class="stage ${s.direction==='return'?'return':''}"><small>${s.kind==='rotor'?'Rotor ':s.kind==='reflector'?'UKW ':''}${s.label}${s.direction==='forward'?' · đi':s.direction==='return'?' · về':''}</small>${A[s.input]} → ${A[s.output]}</div>`).join(''):'';
  drawSignal(t,p);const start=Math.max(0,total-100);let html='';for(let i=total-1;i>=start;i--){let tr=traces[i];html+=`<tr class="${i===index?'selected':''}"><td>${i+1}</td><td>${tr.input} → ${tr.output}</td><td>${letters(tr.before)} → ${letters(tr.after)}</td><td>${tr.stepped.map((v,j)=>v?config.rotors[j]:'').filter(Boolean).join(', ')}</td><td><button class="btn ghost small" data-inspect="${i}">Xem</button></td></tr>`;}$('historyBody').innerHTML=html;$('historyInfo').textContent=total?'Hiển thị '+Math.min(100,total)+' bước gần nhất / tổng '+total+'. File CSV chứa toàn bộ nhật ký.':'Bấm một phím để bắt đầu ghi nhật ký.';$('exportCsv').disabled=!total;
 }
 function drawSignal(trace,positions){const n=config.rotors.length,W=n===4?990:860,H=480,top=84,dy=13.5,y=i=>top+i*dy,blockW=75,refX=60,rotorX=i=>185+i*140,plugX=rotorX(n),right=plugX+blockW+62;
  const viewWidth=Math.max(W,right+45);let bg='',wires='',path='',labels='';const line=(x1,y1,x2,y2,color,width=1,opacity=1)=>`<path d="M ${x1} ${y1} L ${x2} ${y2}" fill="none" stroke="${color}" stroke-width="${width}" opacity="${opacity}"/>`;
  const component=(x,name,sub)=>{bg+=`<rect x="${x}" y="65" width="${blockW}" height="368" rx="5" fill="#202b23" stroke="#455342"/><text x="${x+blockW/2}" y="31" text-anchor="middle" fill="#dedfce" font-size="12">${name}</text><text x="${x+blockW/2}" y="49" text-anchor="middle" fill="#8eaa90" font-size="9">${sub}</text>`;for(let j=0;j<26;j++)labels+=`<text x="${x-9}" y="${y(j)+3}" text-anchor="middle" fill="#95a58d" font-size="8">${A[j]}</text><text x="${x+blockW+9}" y="${y(j)+3}" text-anchor="middle" fill="#95a58d" font-size="8">${A[j]}</text>`;};
  component(refX,'UKW '+config.reflector.replace('-thin','′'),'REFLECTOR');for(let i=0;i<n;i++){component(rotorX(i),config.rotors[i],A[positions[i]]+' / R '+A[config.rings[i]]+(n===4&&i===0?' · TĨNH':''));for(let v=0;v<26;v++)wires+=line(rotorX(i)+blockW,y(v),rotorX(i),y(E.pass(config.rotors[i],v,positions[i],config.rings[i])),'#95ae99',.6,.14);}
  component(plugX,'PLUGBOARD',config.plugs.length+' CẶP / ETW = A–Z');for(let v=0;v<26;v++){wires+=line(plugX+blockW,y(v),plugX,y(machine.plug[v]),'#95ae99',.6,.14);const r=A.indexOf(E.REF[config.reflector][v]);if(v<r)wires+=`<path d="M ${refX+blockW} ${y(v)} C ${refX-20} ${y(v)}, ${refX-20} ${y(r)}, ${refX+blockW} ${y(r)}" fill="none" stroke="#95ae99" stroke-width=".6" opacity=".16"/>`;}
  if(trace){let currentX=right,currentV=A.indexOf(trace.input);for(const s of trace.stages){let sx,ex;if(s.kind==='plug'){sx=s.direction==='forward'?plugX+blockW:plugX;ex=s.direction==='forward'?plugX:plugX+blockW;}else if(s.kind==='rotor'){sx=s.direction==='forward'?rotorX(s.index)+blockW:rotorX(s.index);ex=s.direction==='forward'?rotorX(s.index):rotorX(s.index)+blockW;}else{sx=refX+blockW;ex=sx;}const color=s.direction==='return'?'#9ccfb2':'#e5c17c';path+=line(currentX,y(currentV),sx,y(s.input),color,2.4);if(s.kind==='reflector'){path+=`<path d="M ${sx} ${y(s.input)} C ${refX-12} ${y(s.input)}, ${refX-12} ${y(s.output)}, ${sx} ${y(s.output)}" fill="none" stroke="#e5c17c" stroke-width="2.7"/>`;}else path+=line(sx,y(s.input),ex,y(s.output),color,2.4);for(const [cx,cy] of [[sx,y(s.input)],[ex,y(s.output)]])path+=`<circle cx="${cx}" cy="${cy}" r="3.1" fill="${color}"/>`;currentX=ex;currentV=s.output;}
   path+=line(currentX,y(currentV),right,y(currentV),'#9ccfb2',2.4);labels+=`<rect x="${right-12}" y="${y(A.indexOf(trace.input))-11}" width="25" height="22" rx="4" fill="#e5c17c"/><text x="${right}" y="${y(A.indexOf(trace.input))+4}" text-anchor="middle" fill="#202719" font-size="12">${trace.input}</text><rect x="${right-12}" y="${y(A.indexOf(trace.output))-11}" width="25" height="22" rx="4" fill="#9ccfb2"/><text x="${right}" y="${y(A.indexOf(trace.output))+4}" text-anchor="middle" fill="#202719" font-size="12">${trace.output}</text>`;}
  $('traceDiagram').innerHTML=`<svg viewBox="0 0 ${viewWidth} ${H}" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="${trace?'Đường điện của chữ '+trace.input+' thành '+trace.output:'Dây nối bên trong máy Enigma'}" style="font-family:ui-monospace,Consolas,monospace"><text x="${right}" y="31" text-anchor="middle" fill="#bdc5b6" font-size="10">PHÍM / ĐÈN</text>${bg}${wires}${path}${labels}<text x="${viewWidth/2}" y="461" text-anchor="middle" fill="#829480" font-size="10">LƯỢT ĐI: PHẢI → TRÁI · LƯỢT VỀ: TRÁI → PHẢI</text></svg>`;
 }
 function openSettings(focusPlug=false){pause();editConfig=E.clone(config);pendingPlug=null;$('settingsError').textContent='';$('modelSelect').value=editConfig.model;renderSettings();$('settingsDialog').showModal();document.body.classList.add('modal-open');requestAnimationFrame(()=>{drawPlugWires();if(focusPlug)$('plugEditor').scrollIntoView({block:'start'});});}
 function options(values,selected,label=x=>x){return values.map(v=>`<option value="${v}"${v===selected?' selected':''}>${label(v)}</option>`).join('');}
 function renderSettings(){const c=editConfig,n=c.rotors.length;$('modelSelect').value=c.model;$('reflectorSelect').innerHTML=options(c.model==='M4'?['B-thin','C-thin']:c.model==='I'?['A','B','C']:['B','C'],c.reflector,r=>r.replace('-thin',' · mỏng'));$('configRotors').classList.toggle('four',n===4);$('configRotors').innerHTML=c.rotors.map((name,i)=>{const greek=n===4&&i===0,available=greek?['Beta','Gamma']:c.model==='I'?['I','II','III','IV','V']:['I','II','III','IV','V','VI','VII','VIII'];const side=greek?'Greek · Đứng yên':i===n-1?'Phải · Nhanh':i===n-2?'Giữa':'Trái · Chậm';return `<div class="config-rotor"><div class="slot-name">${side}</div><label for="edit-rotor-${i}">Loại rotor</label><select id="edit-rotor-${i}" data-setting="rotors" data-index="${i}">${options(available,name)}</select><label for="edit-ring-${i}">Vòng · Ringstellung</label><select id="edit-ring-${i}" data-setting="rings" data-index="${i}">${options(Array.from({length:26},(_,j)=>j),c.rings[i],j=>A[j]+' · '+String(j+1).padStart(2,'0'))}</select><label for="edit-pos-${i}">Cửa sổ ban đầu</label><select id="edit-pos-${i}" data-setting="positions" data-index="${i}">${options(Array.from({length:26},(_,j)=>j),c.positions[i],j=>A[j]+' · '+String(j+1).padStart(2,'0'))}</select></div>`;}).join('');renderPlugEditor();}
 function renderPlugEditor(){const plugs=editConfig.plugs,used=plugs.join('');$('plugSockets').innerHTML=rows.map(row=>'<div class="plug-row">'+[...row].map(c=>`<button type="button" class="socket ${used.includes(c)?'paired':''} ${pendingPlug===c?'pending':''}" data-socket="${c}" aria-label="Ổ ${c}${used.includes(c)?', nối '+plugs.find(p=>p.includes(c)).split('').find(v=>v!==c):', chưa nối'}" aria-pressed="${pendingPlug===c}">${c}</button>`).join('')+'</div>').join('');$('plugText').value=plugs.join(' ');$('plugCount').textContent=plugs.length+' / 13 cặp';$('editPairChips').innerHTML=plugs.map(p=>`<button type="button" class="pair-chip" data-remove-pair="${p}" title="Tháo cặp ${p}">${p[0]} ↔ ${p[1]} ×</button>`).join('');$('plugEditorHint').textContent=pendingPlug?'Đã chọn '+pendingPlug+'. Chọn thêm một ổ trống để nối (bấm lại để hủy).':'Bấm hai ổ trống để nối dây. Bấm ổ đang nối để tháo cặp đó. Tối đa 13 cặp; thường dùng 10.';requestAnimationFrame(drawPlugWires);}
 function drawPlugWires(){if(!$('settingsDialog').open||!editConfig)return;const rect=$('plugBoard').getBoundingClientRect(),svg=$('plugWires'),colors=['#b3c590','#bba078','#8eb6ab','#c6ae8f','#a9b4c8'];svg.setAttribute('viewBox',`0 0 ${rect.width} ${rect.height}`);svg.innerHTML=editConfig.plugs.map((p,i)=>{const a=$('plugSockets').querySelector(`[data-socket="${p[0]}"]`).getBoundingClientRect(),b=$('plugSockets').querySelector(`[data-socket="${p[1]}"]`).getBoundingClientRect(),x1=a.left-rect.left+a.width/2,x2=b.left-rect.left+b.width/2,y1=a.bottom-rect.top,y2=b.bottom-rect.top,bend=Math.min(rect.height-3,Math.max(y1,y2)+21+(i%3)*6);return `<path d="M${x1},${y1} C${x1},${bend} ${x2},${bend} ${x2},${y2}" stroke="#080e09" stroke-width="6" fill="none"/><path d="M${x1},${y1} C${x1},${bend} ${x2},${bend} ${x2},${y2}" stroke="${colors[i%colors.length]}" stroke-width="3" fill="none"/>`;}).join('');}
 function applyPlugText(){try{editConfig.plugs=E.parsePlugs($('plugText').value);pendingPlug=null;$('settingsError').textContent='';renderPlugEditor();return true;}catch(e){$('settingsError').textContent=e.message;return false;}}
 function clickSocket(c){if($('plugText').value!==editConfig.plugs.join(' ')&&!applyPlugText())return;const pair=editConfig.plugs.find(p=>p.includes(c));if(pair){editConfig.plugs=editConfig.plugs.filter(p=>p!==pair);pendingPlug=null;}else if(pendingPlug===c)pendingPlug=null;else if(pendingPlug){editConfig.plugs=E.parsePlugs([...editConfig.plugs,pendingPlug+c].join(' '));pendingPlug=null;}else pendingPlug=c;renderPlugEditor();$('settingsError').textContent='';}
 function makeSession(){return {schema:'enigma-lab',version:1,config:E.clone(config),text:source,processed:traces.length,grouped:$('groupOutput').checked,speed:Number($('speed').value)};}
 function restoreSession(data){if(!data||data.schema!=='enigma-lab'||data.version!==1)throw new Error('File không đúng định dạng Enigma Lab v1.');const c=E.validate(data.config);if(typeof data.text!=='string'||data.text.length>40000)throw new Error('Văn bản trong phiên quá dài hoặc không hợp lệ.');const plain=E.normalize(data.text);if(plain.length>MAX||!Number.isInteger(data.processed)||data.processed<0||data.processed>plain.length)throw new Error('Số bước đã xử lý không hợp lệ.');useConfig(c,data.text);for(let i=0;i<data.processed;i++)pressNext(false);$('groupOutput').checked=data.grouped!==false;$('speed').value=Number.isInteger(data.speed)&&data.speed>=1&&data.speed<=12?data.speed:4;updateSpeed();update();saveSoon();}
 function saveSoon(){clearTimeout(saveTimer);if(!storageEnabled)return;saveTimer=setTimeout(()=>{try{localStorage.setItem(STORAGE,JSON.stringify(makeSession()));$('storageStatus').textContent='Đã nhớ phiên';}catch(e){$('storageStatus').textContent='Không thể lưu tại trình duyệt';}},300);}
 function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
 async function copyResult(){const text=grouped(output());if(!text)return;try{if(!navigator.clipboard)throw new Error('fallback');await navigator.clipboard.writeText(text);toast('Đã sao chép kết quả.');}catch(e){const area=document.createElement('textarea');area.value=text;area.style.cssText='position:fixed;left:-9999px';document.body.append(area);area.select();let ok=false;try{ok=document.execCommand('copy');}catch(e){}area.remove();if(ok)toast('Đã sao chép kết quả.');else{const range=document.createRange();range.selectNodeContents($('outputText'));const selection=getSelection();selection.removeAllRanges();selection.addRange(range);toast('Kết quả đã được chọn. Nhấn Ctrl+C / Cmd+C để sao chép.');}}}
 function runTests(show=false){const tests=E.selfTests(),pass=tests.filter(t=>t.ok).length;$('testBadge').textContent=pass+' / '+tests.length+' kiểm tra đạt';$('diagnostics').innerHTML=tests.map(t=>`<div class="test-row ${t.ok?'':'fail'}">${t.ok?'✓':'✕'} ${t.name}${t.ok?'':' — '+t.error}</div>`).join('');if(show)$('diagnostics').hidden=false;return tests;}
 function updateSpeed(){$('speedLabel').textContent=$('speed').value+' chữ/s';}
 initKeys();buildRotors();update();runTests();
 document.querySelectorAll('[data-tab]').forEach(b=>{b.addEventListener('click',()=>setTab(b.dataset.tab));b.addEventListener('keydown',e=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;e.preventDefault();const tabs=[...document.querySelectorAll('[data-tab]')],i=tabs.indexOf(b),last=tabs.length-1,next=e.key==='Home'?0:e.key==='End'?last:(i+(e.key==='ArrowRight'?1:last))%tabs.length;tabs[next].focus();setTab(tabs[next].dataset.tab);});});
 $('guideBtn').addEventListener('click',()=>setTab('guide'));$('inspectBtn').addEventListener('click',()=>setTab('signal'));$('guideExample').addEventListener('click',()=>preset('hello'));$('soundBtn').addEventListener('click',()=>{sound=!sound;$('soundBtn').textContent='Âm thanh: '+(sound?'Bật':'Tắt');$('soundBtn').setAttribute('aria-pressed',String(sound));if(sound)tickSound();});
 $('messageInput').addEventListener('input',e=>{source=e.target.value;normalized=E.normalize(source);const tooLong=normalized.length>MAX;if(tooLong){normalized=normalized.slice(0,MAX);source=normalized;e.target.value=source;}$('inputError').hidden=!tooLong;$('inputError').textContent='Đã giới hạn nội dung còn 10.000 chữ A–Z.';clearRun();$('presetNotice').hidden=true;update();saveSoon();});
 $('sampleSelect').addEventListener('change',e=>preset(e.target.value));$('playBtn').addEventListener('click',play);$('stepBtn').addEventListener('click',next);$('fastBtn').addEventListener('click',fast);$('signalStep').addEventListener('click',next);$('signalPlay').addEventListener('click',play);$('undoBtn').addEventListener('click',undo);$('rewindBtn').addEventListener('click',()=>reset(true));$('newBtn').addEventListener('click',()=>reset(false));$('speed').addEventListener('input',()=>{updateSpeed();saveSoon();});$('groupOutput').addEventListener('change',()=>{update();saveSoon();});
 $('decryptBtn').addEventListener('click',()=>{const result=output();pause(false);source=result;normalized=result;clearRun();$('presetNotice').textContent='Đã nạp bản mã và khôi phục khóa ban đầu '+letters(config.positions)+'. Bấm Chạy bản tin để giải mã.';$('presetNotice').hidden=false;update();saveSoon();toast('Đã sẵn sàng giải mã bằng cùng khóa khởi đầu.');});
 document.addEventListener('keydown',e=>{if($('settingsDialog').open||e.ctrlKey||e.metaKey||e.altKey||e.isComposing||e.repeat||e.target.closest('input,textarea,select,[contenteditable=true]'))return;if(activeTab!=='machine')return;if(/^[a-zA-Z]$/.test(e.key)){e.preventDefault();manualPress(e.key.toUpperCase());}else if(e.key==='Backspace'){e.preventDefault();undo();}});
 $('traceSelect').addEventListener('change',e=>{inspect=Number(e.target.value);renderTrace();});$('tracePrev').addEventListener('click',()=>selectTrace((inspect<0?traces.length-1:inspect)-1));$('traceNext').addEventListener('click',()=>selectTrace((inspect<0?traces.length-1:inspect)+1));$('historyBody').addEventListener('click',e=>{const b=e.target.closest('[data-inspect]');if(b){selectTrace(Number(b.dataset.inspect));$('traceDiagram').scrollIntoView({block:'start',behavior:'smooth'});}});
 $('settingsBtn').addEventListener('click',()=>openSettings());$('plugBtn').addEventListener('click',()=>openSettings(true));for(const id of ['closeSettings','cancelSettings'])$(id).addEventListener('click',()=>$('settingsDialog').close());$('modelSelect').addEventListener('change',e=>{const plugs=editConfig.plugs;editConfig=E.defaultConfig(e.target.value);editConfig.plugs=plugs;pendingPlug=null;$('settingsError').textContent='';renderSettings();});$('reflectorSelect').addEventListener('change',e=>editConfig.reflector=e.target.value);
 $('configRotors').addEventListener('change',e=>{const s=e.target.dataset.setting;if(s)editConfig[s][Number(e.target.dataset.index)]=s==='rotors'?e.target.value:Number(e.target.value);});$('plugSockets').addEventListener('click',e=>{const b=e.target.closest('[data-socket]');if(b)clickSocket(b.dataset.socket);});$('editPairChips').addEventListener('click',e=>{const b=e.target.closest('[data-remove-pair]');if(b){editConfig.plugs=editConfig.plugs.filter(p=>p!==b.dataset.removePair);pendingPlug=null;renderPlugEditor();}});$('applyPlugText').addEventListener('click',applyPlugText);$('clearPlugs').addEventListener('click',()=>{editConfig.plugs=[];pendingPlug=null;$('settingsError').textContent='';renderPlugEditor();});
 $('settingsForm').addEventListener('submit',e=>{e.preventDefault();if(pendingPlug){$('settingsError').textContent='Hãy hoàn tất hoặc hủy ổ cắm đang chọn.';return;}if(!applyPlugText())return;try{const valid=E.validate(editConfig);useConfig(valid);$('settingsDialog').close();toast('Đã áp dụng khóa mới. Máy sẵn sàng.');}catch(err){$('settingsError').textContent=err.message;}});window.addEventListener('resize',()=>requestAnimationFrame(drawPlugWires));
 $('selfTestBtn').addEventListener('click',()=>runTests(true));$('copyBtn').addEventListener('click',copyResult);$('exportSession').addEventListener('click',()=>download('enigma-session.json',JSON.stringify(makeSession(),null,2),'application/json'));$('importSession').addEventListener('click',()=>$('importFile').click());$('importFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;pause();try{if(file.size>500000)throw new Error('File phiên vượt quá 500 KB.');const data=JSON.parse(await file.text());restoreSession(data);toast('Đã khôi phục phiên và vị trí rotor.');}catch(err){toast('Không thể nhập: '+err.message);}finally{e.target.value='';}});
 $('exportText').addEventListener('click',()=>download('enigma-ket-qua.txt',grouped(output())+'\n','text/plain;charset=utf-8'));$('exportCsv').addEventListener('click',()=>{const header='step,input,output,before,after,moving_rotors\n';const body=traces.map((t,i)=>[i+1,t.input,t.output,letters(t.before),letters(t.after),t.stepped.map((v,j)=>v?config.rotors[j]:'').filter(Boolean).join(' ')].join(',')).join('\n');download('enigma-nhat-ky.csv','\ufeff'+header+body,'text/csv;charset=utf-8');});
 $('remember').addEventListener('change',e=>{storageEnabled=e.target.checked;if(storageEnabled)saveSoon();else{clearTimeout(saveTimer);try{localStorage.removeItem(STORAGE);$('storageStatus').textContent='Đã tắt và xóa phiên đã nhớ';}catch(e){$('storageStatus').textContent='Không truy cập được bộ nhớ';}}});
 try{const saved=localStorage.getItem(STORAGE);if(saved){restoreSession(JSON.parse(saved));storageEnabled=true;$('remember').checked=true;$('storageStatus').textContent='Đã khôi phục phiên';}}catch(e){$('storageStatus').textContent='Không có phiên hợp lệ để khôi phục';}

 $('dockMachine').addEventListener('click',()=>{setTab('machine');$('machineArea').scrollIntoView({block:'start',behavior:'auto'});});
 $('dockMessage').addEventListener('click',()=>{setTab('machine');$('messageArea').scrollIntoView({block:'start',behavior:'auto'});});
 $('dockPlay').addEventListener('click',play);
 $('dockSettings').addEventListener('click',()=>openSettings());
 $('settingsDialog').addEventListener('close',()=>document.body.classList.remove('modal-open'));
 $('diagramZoom').addEventListener('click',()=>{const fit=$('traceDiagram').classList.toggle('fit');$('diagramZoom').textContent=fit?'Phóng to sơ đồ':'Vừa màn hình';$('diagramZoom').setAttribute('aria-pressed',String(!fit));$('diagramHint').textContent=fit?'Toàn cảnh đường tín hiệu':'Vuốt ngang để theo đường điện';requestAnimationFrame(()=>{$('traceDiagram').scrollLeft=fit?0:$('traceDiagram').scrollWidth;});});
 const refreshTyping=()=>requestAnimationFrame(()=>{const e=document.activeElement;document.body.classList.toggle('typing',Boolean(e&&e.matches('textarea,input:not([type]),input[type=text],input[type=search],input[type=email],input[type=number],input[type=password]')));});
 document.addEventListener('focusin',refreshTyping);document.addEventListener('focusout',refreshTyping);
 window.addEventListener('pagehide',()=>{if(storageEnabled){try{localStorage.setItem(STORAGE,JSON.stringify(makeSession()));}catch(e){}}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&running)pause();});
 // Read-only convenience for local verification and educational console experiments.
 window.EnigmaLab={core:E,getState:()=>({config:E.clone(config),source,normalized,processed:traces.length,output:output(),positions:[...machine.positions],running}),selfTests:E.selfTests,applyConfig:(c,notice='')=>useConfig(c,'',notice),setTab,toast,download};
})();
